name: i_am_rich
description: A new Flutter project.
version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  provider: ^6.0.3
  audioplayers: ^1.1.1




dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
      sdk: flutter
  test: ^1.14.4
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - images/flutter.png
    - images/MicrosoftTeams-image.png
    - images/dice1.png
    - images/dice2.png
    - images/dice3.png
    - images/dice4.png
    - images/dice5.png
    - images/dice6.png


  fonts:
    - family: Satisfy
      fonts:
        - asset: fonts/Satisfy-Regular.ttf

